
name: Test

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
      - name: Build Gem and Push
        env:
          PACKAGES_WRITE_TOKEN: ${secrets.PACKAGES_WRITE_TOKEN}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials
          echo "---" >$HOME/.gem/credentials
          echo ":github: Bearer ${PACKAGES_WRITE_TOKEN}" >> $HOME/.gem/credentials

          gem build *.gemspec
          gem push --key github --host https://rubygems.pkg.github.com/zakizaki-ri9-sandbox *.gem
