
name: Test

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
      - name: Setup release credentials
        env:
          GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}
        run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          echo ":github: Bearer aaa" >> ~/.gem/credentials
          cat ~/.gem/credentials
      - name: Build Gem and Push
        run: |
          gem build *.gemspec
          gem push --key github --host "https://rubygems.pkg.github.com/zakizaki-ri9-sandbox" ./*.gem
