
name: Test

on:
  registry_package:
    types: [published]

jobs:
  update_gem_version_for_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
          working-directory: .github/update_gem_version_for_repo
      - name: Test
        run: |
            pwd
            ruby main.rb
