
name: Test

on:
  registry_package:
    types: [published]

defaults:
  run:
    working-directory: ./.github/update_gem_version_for_repo

jobs:
  update_gem_version_for_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
          working-directory: ./.github/update_gem_version_for_repo
      - name: Test
        env:
          GITHUB_TOKEN: ${secrets.PACKAGES_WRITE_TOKEN}
        run: |
            pwd
            bundle exec ruby main.rb
